### ISSUE TITLE
Is there a way to extract the SVG of a component from this library?

### ISSUE THREAD

**Issue by therealsujitk** [0xfe/vexflow#1616]
### Question

I'd like to extract certain SVG elements from this library and use them as icons in my frontend (for example: a treble clef or a quarter note, with 24px width). Would this be possible through code? (It'd prefer not to do this manually)

**Comment by AaronDavidNewman** [comment]
You mean on your web page?  Sure.  Just get the font, you don't even need the library:


``` css
.icon-bravura {
  font-family: 'Bravura'!important;
  font-size: 24px;
  position: absolute;
  top: calc(50% - 12px);
}
...
.icon-accidentalFlat:before {
  content: "\e260";
}
```
